POSTGRES:
  USER: "postgres"
  PASSWORD: "postgres"
  HOST: "postgres" 
  PORT: "5432"
  DATABASE_NAME: "rag_db"
  SQLALCHEMY_ECHO: "true"

# Config connect db at local
# POSTGRES:
#   USER: "postgres"
#   PASSWORD: "123456"
#   HOST: "localhost" 
#   PORT: "5432"
#   DATABASE_NAME: "rag"
#   SQLALCHEMY_ECHO: "true"